-- Add Sample Dream Companies for Specific User
-- Run this in your Supabase SQL Editor to add sample companies to your account

-- Replace 'your-user-id-here' with your actual user ID: aa2ab1e3-d6ec-4f31-b2a2-4fd4f40eff75

INSERT INTO dream_companies (
  user_id,
  name,
  logo_url,
  website_url,
  industry,
  company_size,
  location,
  founded_year,
  employee_count,
  remote_policy,
  flexibility_score,
  timezone_flexibility,
  python_usage,
  tech_stack,
  python_frameworks,
  salary_min,
  salary_max,
  salary_currency,
  salary_level,
  benefits,
  work_life_balance,
  learning_opportunities,
  career_growth,
  diversity_score,
  hiring_difficulty,
  average_interview_process,
  response_rate,
  status,
  priority,
  notes,
  glassdoor_rating,
  glassdoor_reviews_count,
  recent_funding_amount,
  recent_funding_date,
  is_actively_hiring,
  target_application_date
) VALUES 
-- GitLab - Remote-first company
(
  'aa2ab1e3-d6ec-4f31-b2a2-4fd4f40eff75'::uuid,
  'GitLab',
  'https://about.gitlab.com/images/press/logo/png/gitlab-logo-gray-rgb.png',
  'https://gitlab.com',
  'DevOps/Software Development',
  'large',
  'Remote-first (San Francisco HQ)',
  2011,
  1300,
  'fully-remote',
  9,
  ARRAY['PST', 'EST', 'GMT', 'CET', 'JST'],
  'primary',
  ARRAY['Ruby', 'Python', 'Go', 'JavaScript', 'Vue.js', 'PostgreSQL', 'Redis', 'Kubernetes', 'Docker', 'Git'],
  ARRAY['Django', 'Flask'],
  120000,
  180000,
  'USD',
  'senior',
  '{
    "healthInsurance": true,
    "dentalVision": true,
    "retirement401k": true,
    "stockOptions": true,
    "unlimitedPTO": true,
    "learningBudget": 2000,
    "homeOfficeStipend": 1500,
    "relocationAssistance": false,
    "visaSponsorship": true
  }'::jsonb,
  9,
  9,
  8,
  9,
  'moderate',
  'Application → Technical Screen → System Design → Final Interview → Reference Check',
  75,
  'targeting',
  'high',
  'All-remote company with transparent culture. Strong Python usage for infrastructure and automation. Great work-life balance and learning opportunities.',
  4.4,
  2100,
  null,
  null,
  true,
  '2024-02-15'
),

-- Stripe - Fintech with strong Python usage
(
  'aa2ab1e3-d6ec-4f31-b2a2-4fd4f40eff75'::uuid,
  'Stripe',
  'https://stripe.com/img/v3/home/social.png',
  'https://stripe.com',
  'Fintech/Payments',
  'large',
  'San Francisco, CA (Remote-friendly)',
  2010,
  4000,
  'hybrid',
  7,
  ARRAY['PST', 'EST'],
  'primary',
  ARRAY['Python', 'Ruby', 'JavaScript', 'Go', 'Java', 'PostgreSQL', 'Redis', 'Kafka', 'Kubernetes'],
  ARRAY['Django', 'Flask', 'FastAPI'],
  140000,
  220000,
  'USD',
  'senior',
  '{
    "healthInsurance": true,
    "dentalVision": true,
    "retirement401k": true,
    "stockOptions": true,
    "unlimitedPTO": true,
    "learningBudget": 3000,
    "homeOfficeStipend": 1000,
    "relocationAssistance": true,
    "visaSponsorship": true
  }'::jsonb,
  8,
  9,
  9,
  8,
  'hard',
  'Application → Phone Screen → Technical Interview → System Design → Onsite (Virtual) → Team Match',
  65,
  'researching',
  'high',
  'Leading fintech company with heavy Python usage. Excellent compensation and growth opportunities. Known for high engineering standards.',
  4.1,
  1800,
  600000000,
  '2023-03-15',
  true,
  '2024-03-01'
),

-- Hugging Face - AI/ML startup
(
  'aa2ab1e3-d6ec-4f31-b2a2-4fd4f40eff75'::uuid,
  'Hugging Face',
  'https://huggingface.co/front/assets/huggingface_logo-noborder.svg',
  'https://huggingface.co',
  'Artificial Intelligence/Machine Learning',
  'startup',
  'New York, NY (Remote-first)',
  2016,
  150,
  'fully-remote',
  9,
  ARRAY['EST', 'PST', 'GMT', 'CET'],
  'primary',
  ARRAY['Python', 'JavaScript', 'TypeScript', 'React', 'PyTorch', 'TensorFlow', 'Docker', 'Kubernetes', 'AWS'],
  ARRAY['FastAPI', 'Django', 'Flask', 'Transformers', 'Datasets'],
  130000,
  200000,
  'USD',
  'senior',
  '{
    "healthInsurance": true,
    "dentalVision": true,
    "retirement401k": false,
    "stockOptions": true,
    "unlimitedPTO": true,
    "learningBudget": 3000,
    "homeOfficeStipend": 1500,
    "relocationAssistance": false,
    "visaSponsorship": true
  }'::jsonb,
  8,
  10,
  9,
  8,
  'hard',
  'Application → Technical Screen → ML System Design → Team Interview → Final Round',
  60,
  'targeting',
  'high',
  'Leading AI/ML company. Heavy Python usage for ML infrastructure. Cutting-edge work in transformers and NLP. High growth potential.',
  4.6,
  120,
  100000000,
  '2023-08-10',
  true,
  '2024-02-01'
),

-- Zapier - Automation platform, fully remote
(
  'aa2ab1e3-d6ec-4f31-b2a2-4fd4f40eff75'::uuid,
  'Zapier',
  'https://cdn.zapier.com/storage/photos/9ec65c79de8ae54080c98946c27e2119.png',
  'https://zapier.com',
  'Automation/SaaS',
  'mid',
  'Remote-first (San Francisco HQ)',
  2011,
  400,
  'fully-remote',
  9,
  ARRAY['PST', 'EST', 'GMT'],
  'primary',
  ARRAY['Python', 'JavaScript', 'Django', 'React', 'PostgreSQL', 'Redis', 'Celery', 'Docker'],
  ARRAY['Django', 'Celery', 'Django REST Framework'],
  110000,
  170000,
  'USD',
  'senior',
  '{
    "healthInsurance": true,
    "dentalVision": true,
    "retirement401k": true,
    "stockOptions": true,
    "unlimitedPTO": true,
    "learningBudget": 2500,
    "homeOfficeStipend": 1500,
    "relocationAssistance": false,
    "visaSponsorship": false
  }'::jsonb,
  9,
  8,
  8,
  7,
  'moderate',
  'Application → Phone Screen → Technical Interview → System Design → Cultural Fit',
  72,
  'researching',
  'high',
  'Automation platform built primarily on Python/Django. Remote-first culture. Great for backend Python developers. Strong API integration work.',
  4.3,
  450,
  null,
  null,
  true,
  '2024-03-15'
);

-- Verify the insertion
SELECT 
  name, 
  status, 
  priority, 
  python_usage, 
  remote_policy,
  salary_min,
  salary_max,
  created_at
FROM dream_companies 
WHERE user_id = 'aa2ab1e3-d6ec-4f31-b2a2-4fd4f40eff75'::uuid
ORDER BY created_at DESC;
