-- Add invitation_note column to contacts table
ALTER TABLE public.contacts 
ADD COLUMN IF NOT EXISTS invitation_note TEXT;

-- Update RLS policies if necessary (usually not needed for new columns on existing table if policy covers 'all' or 'update')
-- Just ensuring the column is available/visible
COMMENT ON COLUMN public.contacts.invitation_note IS 'Personalized LinkedIn invitation note generated by AI';
